---

stages:
  - prepare
  - build
  - release

prepare:
  stage: prepare
  tags:
    - blackikeeagledocker
  script:
    - docker pull blackikeeagle/alpine:3.5
  only:
    - master

build:
  stage: build
  tags:
    - blackikeeagledocker
  script:
    - ./build.sh
  only:
    - master

release:
  stage: release
  tags:
    - blackikeeagledocker
  script:
    - docker push blackikeeagle/vimdeck
  only:
    - master
